- gateway-service/build.gradle
- gateway-service/src/main/resources/application-local.yml
Spring Cloud Gateway 서비스에 WebFlux Swagger UI 추가하여 통합. 라우팅 설정으로 GateWay
WebFlux Swagger UI에 각 서비스의 Swagger UI 경로를 추가하고 라우팅 설정.
주의사항. GateWay의
Swaager UI 라우팅은 AuthorizationFilter를 받지 않아야 하므로 우선적으로 라우팅 설정되어야함.
스웨거 통합 정리 글 #51 
Closes #51
> feat: Swagger UI 통합

- buddy-service/src/main/java/com/freediving/buddyservice/adapter/in/web/v1/CreateBuddyEventControllerV1.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/in/web/v1/CreateBuddyEventRequestV1.java
- buddy-service/src/main/java/com/freediving/buddyservice/domain/CreatedBuddyEvent.java
- buddy-service/src/main/resources/application-local.yml
버디 이벤트 생성 API
- 요청, 응답, API  스웨거 설명 추가.
BuddyService local 프로파일 yml 포트 고정.
> docs: 버디 이벤트 생성 API 스웨거 정보 추가.

- gateway-service/src/main/resources/application-local.yml
- member-service/build.gradle
- member-service/src/main/java/com/freediving/authservice/adapter/in/web/OauthController.java
- member-service/src/main/java/com/freediving/authservice/adapter/in/web/dto/UserLoginResponse.java
- member-service/src/main/java/com/freediving/memberservice/config/SwaggerConfig.java
- member-service/src/main/resources/application-local.yml
- Gateway 내 MemberService 라우팅 설정
- MemberService Swagger 적용
> #59 - MemberService Swagger 초기 설정

- .github/workflows/member-service.yml
- member-service/appspec.yml
- member-service/scripts/deploy.sh
- MemberService CI & CD 적용을 위한 PR 요청
> feat: #41 - MemberService CodeDeploy 설정 추가

- .github/workflows/member-service.yml
- member-service/scripts/deploy.sh
- Swagger 적용 
- CodeDeploy 배포 적용
> #41 - MemberService CI & CD 구축

- community-service/src/main/java/com/freediving/communityservice/adapter/in/dto/ArticleWriteRequest.java
- community-service/src/main/java/com/freediving/communityservice/adapter/in/web/DefaultRestControllerAdvice.java
- community-service/src/main/java/com/freediving/communityservice/adapter/in/web/command/ArticleCommandController.java
- community-service/src/main/java/com/freediving/communityservice/adapter/in/web/command/BoardCommandController.java
- community-service/src/main/java/com/freediving/communityservice/adapter/in/web/query/ArticleQueryController.java
- community-service/src/main/java/com/freediving/communityservice/adapter/in/web/query/BoardQueryController.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/dto/article/ArticleContent.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/article/ArticleJpaEntity.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/article/ArticlePersistenceAdapter.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/article/ArticlePersistenceMapper.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/board/BoardJpaEntity.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/board/BoardPersistenceAdapter.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/board/BoardPersistenceMapper.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/comment/CommentJpaEntity.java
- community-service/src/main/java/com/freediving/communityservice/application/port/in/ArticleCommand.java
- community-service/src/main/java/com/freediving/communityservice/application/port/in/ArticleReadCommand.java
- community-service/src/main/java/com/freediving/communityservice/application/port/in/ArticleUseCase.java
- community-service/src/main/java/com/freediving/communityservice/application/port/in/ArticleWriteCommand.java
- community-service/src/main/java/com/freediving/communityservice/application/port/in/BoardWriteCommand.java
- community-service/src/main/java/com/freediving/communityservice/application/port/out/ArticleReadPort.java
- community-service/src/main/java/com/freediving/communityservice/application/port/out/ArticleWritePort.java
- community-service/src/main/java/com/freediving/communityservice/application/port/out/BoardReadPort.java
- community-service/src/main/java/com/freediving/communityservice/application/port/out/BoardWritePort.java
- community-service/src/main/java/com/freediving/communityservice/application/service/ArticleService.java
- community-service/src/main/java/com/freediving/communityservice/application/service/BoardService.java
- community-service/src/main/java/com/freediving/communityservice/config/JpaConfig.java
- community-service/src/main/java/com/freediving/communityservice/domain/Article.java
- community-service/src/main/java/com/freediving/communityservice/domain/Comment.java
> feat: #32 - Community Service 주요 기능 구현

- member-service/build.gradle
- member-service/src/main/java/com/freediving/MemberServiceApplication.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/dto/CreateUserRequest.java
- member-service/src/main/java/com/freediving/memberservice/config/ConfigurationPropertyConfig.java
- member-service/src/main/java/com/freediving/memberservice/config/DiscoveryConfig.java
- member-service/src/main/java/com/freediving/memberservice/config/FeignConfig.java
- member-service/src/main/java/com/freediving/memberservice/config/JpaConfig.java
- member-service/src/test/java/com/freediving/memberservice/adapter/in/web/CreateUserControllerUnitTest.java
- member-service/src/test/java/com/freediving/memberservice/adapter/in/web/FindUserControllerUnitTest.java
- member-service/src/test/java/com/freediving/memberservice/adapter/out/persistence/CreateUserPersistenceAdapterUnitTest.java
- member-service/src/test/java/com/freediving/memberservice/adapter/out/persistence/UserJpaRepositoryTest.java
- member-service/src/test/java/com/freediving/memberservice/application/port/in/CreateUserCommandUnitTest.java
- member-service/src/test/java/com/freediving/memberservice/application/service/CreateUserServiceUnitTest.java
- member-service/src/test/java/com/freediving/memberservice/custom/WithMockCustomUser.java
- member-service/src/test/java/com/freediving/memberservice/custom/WithMockCustomUserSecurityContextFactory.java
- member-service/src/test/java/com/freediving/memberservice/fixture/CreateUserCommandFixture.java
- member-service/src/test/java/com/freediving/memberservice/fixture/SecurityContextFixture.java
- member-service/src/test/java/com/freediving/memberservice/fixture/UserFixture.java
- Test 의존성 분리를 위한 MemberServiceApplication Configuration 분리
- User 생성 및 조회 단위 테스트 작성
> #75 - MemberService 유저 단위 테스트 작성

- member-service/src/main/java/com/freediving/memberservice/config/ConfigurationPropertyConfig.java
- member-service/src/main/java/com/freediving/memberservice/config/DiscoveryConfig.java
- member-service/src/main/java/com/freediving/memberservice/config/FeignConfig.java
- 테스트 환경에서 Configuration 정보를 분리해서 사용하기 위한 basePackages 지정
> #75 - Configuration basePackages 지정

- member-service/src/main/java/com/freediving/authservice/adapter/in/web/dto/UserLoginResponse.java
- member-service/src/main/java/com/freediving/authservice/domain/OauthUser.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/CreateUserController.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/FindUserController.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/dto/CreateUserResponse.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/dto/FindUserResponse.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/dto/FindUserServiceResponse.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/CreateUserPersistenceAdapter.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/FindUserPersistenceAdapter.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/UserJpaEntity.java
- member-service/src/main/java/com/freediving/memberservice/application/port/in/FindUserListQuery.java
- member-service/src/main/java/com/freediving/memberservice/application/port/in/FindUserUseCase.java
- member-service/src/main/java/com/freediving/memberservice/application/port/in/NicknameGenerator.java
- member-service/src/main/java/com/freediving/memberservice/application/port/out/FindUserPort.java
- member-service/src/main/java/com/freediving/memberservice/application/service/FindUserService.java
- member-service/src/main/java/com/freediving/memberservice/config/SecurityConfig.java
- member-service/src/main/java/com/freediving/memberservice/domain/User.java
- member-service/src/main/java/com/freediving/memberservice/filter/CustomAuthenticationFilter.java
- member-service/src/test/java/com/freediving/memberservice/adapter/in/web/FindUserControllerUnitTest.java
- member-service/src/test/java/com/freediving/memberservice/adapter/out/persistence/CreateUserPersistenceAdapterUnitTest.java
- member-service/src/test/java/com/freediving/memberservice/fixture/FindUserServiceResponseFixture.java
- member-service/src/test/java/com/freediving/memberservice/fixture/UserEntityFixture.java
- 마이크로서비스 간 유저 인터페이스 조회 용 API 추가 
- 유저 생성 시 랜덤 닉네임 기능 추가 
- 유저 인터페이스 조회 컨트롤러 단위 테스트 추가
> #86 - MemberService 유저 인터페이스 조회 추가

- member-service/build.gradle
- member-service/src/main/java/com/freediving/memberservice/config/SecurityConfig.java
- member-service/src/main/java/com/freediving/memberservice/filter/CustomAuthenticationFilter.java
- member-service/src/main/resources/application-local.yml
- 로컬 서버 RDBMS 변경 (Postgres -> H2 인메모리 DB) 
- 로컬 서버 포트 변경 (랜덤포트 -> 50000)
- 시큐리티 설정 변경 (H2 사용 가능)
> feat: #92 - 로컬 DB 인메모리 변경

- member-service/src/main/java/com/freediving/authservice/adapter/in/web/CreateImgController.java
- member-service/src/main/java/com/freediving/authservice/adapter/in/web/DeleteImgController.java
- member-service/src/main/java/com/freediving/authservice/adapter/in/web/ImgController.java
- member-service/src/main/java/com/freediving/authservice/adapter/in/web/dto/CreateImgResponse.java
- member-service/src/main/java/com/freediving/authservice/adapter/in/web/dto/DeleteImgRequest.java
- member-service/src/main/java/com/freediving/authservice/adapter/out/external/aws/AwsImgExternalAdapter.java
- member-service/src/main/java/com/freediving/authservice/adapter/out/persistence/img/CreateImgPersistenceAdapter.java
- member-service/src/main/java/com/freediving/authservice/adapter/out/persistence/img/ImgJpaEntity.java
- member-service/src/main/java/com/freediving/authservice/adapter/out/persistence/img/ImgJpaRepository.java
- member-service/src/main/java/com/freediving/authservice/adapter/out/persistence/token/CreateTokenPersistenceAdapter.java
- member-service/src/main/java/com/freediving/authservice/adapter/out/persistence/token/TokenJpaEntity.java
- member-service/src/main/java/com/freediving/authservice/adapter/out/persistence/token/TokenJpaRepository.java
- member-service/src/main/java/com/freediving/authservice/application/port/in/CreateImgUseCase.java
- member-service/src/main/java/com/freediving/authservice/application/port/in/DeleteImgCommand.java
- member-service/src/main/java/com/freediving/authservice/application/port/in/DeleteImgUseCase.java
- member-service/src/main/java/com/freediving/authservice/application/port/out/CreateImgPort.java
- member-service/src/main/java/com/freediving/authservice/application/port/out/DeleteImgPort.java
- member-service/src/main/java/com/freediving/authservice/application/port/out/ImgPort.java
- member-service/src/main/java/com/freediving/authservice/application/service/CreateImgService.java
- member-service/src/main/java/com/freediving/authservice/application/service/DeleteImgService.java
- member-service/src/main/java/com/freediving/authservice/application/service/ImgService.java
- member-service/src/main/java/com/freediving/authservice/config/AwsConfigProperties.java
- member-service/src/main/java/com/freediving/authservice/util/ImgUtils.java
- member-service/src/main/java/com/freediving/authservice/util/JwtTokenUtils.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/FindUserController.java
- member-service/src/main/resources/application-local.yml
- 이미지 등록 시 CloudFront 반환 값 추가 
- 이미지 삭제 서비스간 API 추가
> #95 - 이미지 등록 / 삭제 API 개발 

- .gitignore
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/DeleteUserController.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/CreateUserPersistenceAdapter.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/DeleteUserPersistenceAdapter.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/FindUserPersistenceAdapter.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/UserJpaEntity.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/UserJpaRepository.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/UserLicenseJpaEntity.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/UserLicenseJpaRepository.java
- member-service/src/main/java/com/freediving/memberservice/application/port/in/DeleteUserUseCase.java
- member-service/src/main/java/com/freediving/memberservice/application/port/out/DeleteUserPort.java
- member-service/src/main/java/com/freediving/memberservice/application/service/DeleteUserService.java
- member-service/src/main/java/com/freediving/memberservice/application/service/FindUserService.java
- member-service/src/main/java/com/freediving/memberservice/domain/LicenseStatus.java
- member-service/src/main/java/com/freediving/memberservice/domain/User.java
- member-service/src/main/java/com/freediving/memberservice/domain/UserStatus.java
- 서비스 간 유저 조회 시 탈퇴한 사용자 / 없는 사용자 닉네임 업데이트
- 유저 상태값 기능 추가 (활성 사용자 / 정지 사용자 / 탈퇴 사용자)
- 유저 탈퇴 기능 추가 (탈퇴 시 유저 상태 값 탈퇴 상태로 업데이트)
> feat: #106 - 유저 탈퇴 기능 추가

- community-service/build.gradle
- community-service/src/main/java/com/freediving/communityservice/CommunityServiceApplication.java
- community-service/src/main/java/com/freediving/communityservice/adapter/in/dto/ArticleImageRequest.java
- community-service/src/main/java/com/freediving/communityservice/adapter/in/dto/ArticleWriteRequest.java
- community-service/src/main/java/com/freediving/communityservice/adapter/in/web/command/ArticleCommandController.java
- community-service/src/main/java/com/freediving/communityservice/adapter/in/web/command/ImageCommandController.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/image/ImageJpaEntity.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/image/ImagePersistenceAdapter.java
- community-service/src/main/java/com/freediving/communityservice/application/port/in/ArticleWriteCommand.java
- community-service/src/main/java/com/freediving/communityservice/application/port/in/ImageUploadCommand.java
- community-service/src/main/java/com/freediving/communityservice/application/port/in/ImageUseCase.java
- community-service/src/main/java/com/freediving/communityservice/application/port/in/dto/ImageInfoCommand.java
- community-service/src/main/java/com/freediving/communityservice/application/port/out/ImageWritePort.java
- community-service/src/main/java/com/freediving/communityservice/application/service/ArticleService.java
- community-service/src/main/java/com/freediving/communityservice/application/service/ImageService.java
- community-service/src/main/resources/data.sql
> feat: #98 - 게시글 내 이미지 등록

- member-service/src/test/java/com/freediving/memberservice/adapter/out/persistence/CreateUserPersistenceAdapterUnitTest.java
- 멤버 서비스 로그인 로직 변경으로 테스트 모킹 추가
> bug: #113 - 멤버 서비스 테스트 모킹 추가

- community-service/src/main/java/com/freediving/communityservice/adapter/in/web/query/ArticleQueryController.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/dto/article/ArticleBriefDto.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/dto/article/ArticleContent.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/dto/article/ArticleContentWithComment.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/dto/image/ImageBriefResponse.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/dto/image/ImageResponse.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/article/ArticlePersistenceAdapter.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/image/ImagePersistenceAdapter.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/image/ImageRepository.java
- community-service/src/main/java/com/freediving/communityservice/application/port/in/ArticleIndexListCommand.java
- community-service/src/main/java/com/freediving/communityservice/application/port/out/ArticleReadPort.java
- community-service/src/main/java/com/freediving/communityservice/application/port/out/ImageReadPort.java
- community-service/src/main/java/com/freediving/communityservice/application/service/ArticleService.java
- community-service/src/main/java/com/freediving/communityservice/domain/Article.java
- community-service/src/main/resources/data.sql
- 게시글 등록시 이미지 저장
- 게시글 조회시 이미지 조회
> feat: #98 - 게시글 이미지 연동

- .github/workflows/member-service-gcp.yml
- .gitignore
- member-service/Dockerfile
- member-service/src/main/java/com/freediving/authservice/adapter/in/web/OauthController.java
- member-service/src/main/java/com/freediving/authservice/adapter/out/external/google/GoogleOauthExternalAdapter.java
- member-service/src/main/java/com/freediving/authservice/adapter/out/external/kakao/KakaoOauthExternalAdapter.java
- member-service/src/main/java/com/freediving/authservice/adapter/out/external/naver/NaverOauthExternalAdapter.java
- member-service/src/main/java/com/freediving/authservice/application/port/in/OauthUseCase.java
- member-service/src/main/java/com/freediving/authservice/application/port/out/OauthFeignPort.java
- member-service/src/main/java/com/freediving/authservice/application/port/out/OauthRedirectUrlPort.java
- member-service/src/main/java/com/freediving/authservice/application/port/out/OauthTemplate.java
- member-service/src/main/java/com/freediving/authservice/application/service/OauthService.java
- member-service/src/main/java/com/freediving/authservice/config/GoogleOauthConfig.java
- member-service/src/main/java/com/freediving/authservice/config/KakaoOauthConfig.java
- member-service/src/main/java/com/freediving/authservice/config/NaverOauthConfig.java
- member-service/src/main/resources/application-local.yml
#113 - 멤버 서비스 GCP 배포 작업 진행
- AWS 배포 -> GCP 배포 작업 추가
- 소셜 로그인 시 프로필 별 URI 제공 기능 추가
> #113 - 멤버 서비스 GCP 배포 작업

- community-service/src/main/java/com/freediving/communityservice/adapter/in/dto/ArticleEditRequest.java
- community-service/src/main/java/com/freediving/communityservice/adapter/in/dto/ArticleImageRequest.java
- community-service/src/main/java/com/freediving/communityservice/adapter/in/dto/ArticleWriteRequest.java
- community-service/src/main/java/com/freediving/communityservice/adapter/in/web/command/ArticleCommandController.java
- community-service/src/main/java/com/freediving/communityservice/adapter/in/web/query/ArticleQueryController.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/article/ArticleJpaEntity.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/article/ArticlePersistenceAdapter.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/image/ImageJpaEntity.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/image/ImagePersistenceAdapter.java
- community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/image/ImageRepository.java
- community-service/src/main/java/com/freediving/communityservice/application/port/in/ArticleEditCommand.java
- community-service/src/main/java/com/freediving/communityservice/application/port/in/dto/ImageInfoCommand.java
- community-service/src/main/java/com/freediving/communityservice/application/port/out/ArticleEditPort.java
- community-service/src/main/java/com/freediving/communityservice/application/port/out/ImageDeletePort.java
- community-service/src/main/java/com/freediving/communityservice/application/port/out/ImageEditPort.java
- community-service/src/main/java/com/freediving/communityservice/application/port/out/ImageWritePort.java
- community-service/src/main/java/com/freediving/communityservice/application/service/ArticleService.java
- community-service/src/main/java/com/freediving/communityservice/domain/Article.java
feat: #116 - 게시글 이미지 CRUD
- 게시글 내 사진 수정시 추가,삭제,순서변경
> Feat/#116 게시글 이미지 CRUD

- buddy-service/src/test/java/com/freediving/divingpool/repository/DivingPoolRepositoryTest.java
- buddy-service/src/test/java/com/freediving/divingpool/service/DivingPoolServiceTest.java
> fix: 다이빙 풀 조회 테스트 버그 픽스

- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/CreateUserPersistenceAdapter.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/FindUserPersistenceAdapter.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/UserLicenseJpaRepository.java
> bug: #139 - 사용자 조회 쿼리 오류 수정

- member-service/src/main/java/com/freediving/authservice/adapter/out/external/OauthResponse.java
- member-service/src/main/java/com/freediving/authservice/adapter/out/external/google/GoogleInfoResponse.java
- member-service/src/main/java/com/freediving/authservice/adapter/out/external/google/GoogleOauthExternalAdapter.java
- member-service/src/main/java/com/freediving/authservice/adapter/out/external/kakao/KakaoOauthExternalAdapter.java
- member-service/src/main/java/com/freediving/authservice/adapter/out/external/naver/NaverOauthExternalAdapter.java
- member-service/src/main/java/com/freediving/authservice/domain/OauthUser.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/CreateUserController.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/dto/CreateUserRequest.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/CreateUserPersistenceAdapter.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/UserJpaEntity.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/UserJpaRepository.java
- member-service/src/main/java/com/freediving/memberservice/application/port/in/CreateUserCommand.java
- member-service/src/test/java/com/freediving/memberservice/adapter/in/web/CreateUserControllerUnitTest.java
- member-service/src/test/java/com/freediving/memberservice/adapter/out/persistence/CreateUserPersistenceAdapterUnitTest.java
- member-service/src/test/java/com/freediving/memberservice/adapter/out/persistence/UserJpaRepositoryTest.java
- member-service/src/test/java/com/freediving/memberservice/application/port/in/CreateUserCommandUnitTest.java
- member-service/src/test/java/com/freediving/memberservice/application/service/CreateUserServiceUnitTest.java
- member-service/src/test/java/com/freediving/memberservice/fixture/CreateUserCommandFixture.java
- member-service/src/test/java/com/freediving/memberservice/fixture/UserFixture.java
- 소셜로그인 유저 식별값 변경(이메일 -> 회원번호)
> refactor: #141 - 소셜로그인 유저 식별값 변경(이메일 -> 회원번호)

- member-service/src/main/java/com/freediving/authservice/adapter/in/web/DeleteImgController.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/FindUserController.java
- member-service/src/main/java/com/freediving/memberservice/config/SecurityConfig.java
- member-service/src/main/java/com/freediving/memberservice/filter/CustomAuthenticationFilter.java
- member-service/src/test/java/com/freediving/memberservice/adapter/in/web/FindUserControllerUnitTest.java
- 서비스간 라우팅 URI 변경 (service -> internal)
> refactor: #143 - 서비스간 라우팅 URI 변경 (service -> internal)

- member-service/src/main/java/com/freediving/authservice/adapter/in/web/TokenController.java
> refactor: #145 - 스웨커 토큰 업데이트 API 예시 변경

- buddy-service/src/main/java/com/freediving/buddyservice/domain/enumeration/BuddyEventConcept.java
- buddy-service/src/main/resources/data.sql
> feat: 버디 컨셉 머메이드 추가

- common/src/main/java/com/freediving/common/domain/member/Diving.java
- common/src/main/java/com/freediving/common/domain/member/FreeDiving.java
- common/src/main/java/com/freediving/common/domain/member/MemberLicenseInfo.java
- common/src/main/java/com/freediving/common/domain/member/ScubaDiving.java
- common/src/main/java/com/freediving/common/response/dto/member/MemberFindUserResponse.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/FindUserController.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/dto/CreateUserRequest.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/dto/FindUserResponse.java
- member-service/src/main/java/com/freediving/memberservice/config/SwaggerResponse.java
- member-service/src/main/java/com/freediving/memberservice/util/TestUserCreator.java
#145 - 유저 조회 Swagger  변경 및 로컬 테스트 유저 생성 기능 추가
> #145 - 유저 조회 Swagger  변경 및 로컬 테스트 유저 생성 기능 추가

- member-service/src/main/java/com/freediving/authservice/adapter/in/web/TokenController.java
- member-service/src/main/java/com/freediving/authservice/adapter/out/persistence/token/FindTokenPersistenceAdapter.java
- member-service/src/main/java/com/freediving/authservice/application/port/in/TokenUseCase.java
- member-service/src/main/java/com/freediving/authservice/application/port/out/FindTokenPort.java
- member-service/src/main/java/com/freediving/authservice/application/service/TokenService.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/HelloController.java
- member-service/src/main/java/com/freediving/memberservice/application/port/in/FindUserUseCase.java
- member-service/src/main/java/com/freediving/memberservice/application/service/FindUserService.java
- member-service/src/main/java/com/freediving/memberservice/util/TestUserCreator.java
테스트 유저 10명으로 변경 및 샘플 토큰 조회 시 유저 아이디 조회할 수 있도록 변경 
- 개발 서버내 테스트 유저 생성 기능 추가
> feat: #145 - local 환경 테스트 유저 생성 기능 추가

- gateway-service/src/main/java/org/freediving/gatewayservice/filter/AuthorizationFilter.java
- member-service/src/main/java/com/freediving/memberservice/filter/CustomAuthenticationFilter.java
- 비로그인 API 요청 기능 추가 (Header User 정보 추가)
- 멤버 서비스 내 비로그인 접속 시 차단되도록 설정
> feat: #145 - 비로그인 API 요청 기능 추가 (Header User 정보 추가)

- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/CreateUserController.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/CreateUserControllerV2.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/dto/CreateUserInfoRequestV2.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/dto/CreateUserProfileRequest.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/CreateUserPersistenceAdapter.java
- member-service/src/main/java/com/freediving/memberservice/application/port/in/CreateUserInfoCommandV2.java
- member-service/src/main/java/com/freediving/memberservice/application/port/in/CreateUserProfileCommand.java
- member-service/src/main/java/com/freediving/memberservice/application/port/in/CreateUserUseCaseV2.java
- member-service/src/main/java/com/freediving/memberservice/application/port/out/CreateUserPort.java
- member-service/src/main/java/com/freediving/memberservice/application/port/out/CreateUserPortV2.java
- member-service/src/main/java/com/freediving/memberservice/application/service/CreateUserService.java
> feat: #145 - 회원가입 프로필 로직 분리 기능 추가

- member-service/build.gradle
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/UpdateUserController.java
- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/dto/UpdateUserInfoRequest.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/dto/UserConceptRequest.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/dto/UserPoolRequest.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/kafka/UserPreferencesProducer.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/CreateUserPersistenceAdapter.java
- member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/UpdateUserPersistenceAdapter.java
- member-service/src/main/java/com/freediving/memberservice/application/port/in/UpdateUserInfoCommand.java
- member-service/src/main/java/com/freediving/memberservice/application/port/in/UpdateUserUseCase.java
- member-service/src/main/java/com/freediving/memberservice/application/port/out/UpdateUserPort.java
- member-service/src/main/java/com/freediving/memberservice/application/service/UpdateUserService.java
- member-service/src/main/resources/application-local.yml
- 버디서비스 카프카 통신 설정 추가 (유저 선호 정보)
- 유저 정보 수정 기능 추가
> #162 - 유저 정보 수정 / 등록 기능 추가

- buddy-service/src/main/java/com/freediving/buddyservice/adapter/in/internallservice/query/InternalController.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/in/web/query/BuddyEventAttributeController.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/externalservice/member/userinfo/MemberServiceAdapter.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/BuddyEventPersistenceAdapter.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/concept/BuddyEventConceptMappingPersistenceAdapter.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/concept/querydsl/BuddyEventConceptMappingRepoDSL.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/concept/querydsl/BuddyEventConceptMappingRepoDSLImpl.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/divingpool/BuddyEventDivingPoolMappingPersistenceAdapter.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/divingpool/querydsl/BuddyEventDivingPoolMappingRepoDSL.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/divingpool/querydsl/BuddyEventDivingPoolMappingRepoDSLImpl.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/join/BuddyEventJoinPersistenceAdapter.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/join/querydsl/BuddyEventJoinRepoDSL.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/join/querydsl/BuddyEventJoinRepoDSLImpl.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/querydsl/listing/GetBuddyEventListingRepoDSL.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/querydsl/listing/GetBuddyEventListingRepoDSLImpl.java
- buddy-service/src/main/java/com/freediving/buddyservice/application/port/in/internalservice/query/InternalUseCase.java
- buddy-service/src/main/java/com/freediving/buddyservice/application/port/out/Internalservice/query/MemberStatus.java
- buddy-service/src/main/java/com/freediving/buddyservice/application/port/out/Internalservice/query/RequestMemberPort.java
- buddy-service/src/main/java/com/freediving/buddyservice/application/port/out/web/query/BuddyEventConceptMappingPort.java
- buddy-service/src/main/java/com/freediving/buddyservice/application/port/out/web/query/BuddyEventDivingPoolMappingPort.java
- buddy-service/src/main/java/com/freediving/buddyservice/application/port/out/web/query/BuddyEventJoinPort.java
- buddy-service/src/main/java/com/freediving/buddyservice/application/port/out/web/query/GetBuddyEventCarouselPort.java
- buddy-service/src/main/java/com/freediving/buddyservice/application/port/out/web/query/GetBuddyEventListingPort.java
- buddy-service/src/main/java/com/freediving/buddyservice/application/service/Internalservice/InternalService.java
- buddy-service/src/main/java/com/freediving/buddyservice/application/service/web/CreateBuddyEventService.java
- buddy-service/src/main/java/com/freediving/buddyservice/application/service/web/GetBuddyEventCarouselService.java
- buddy-service/src/main/java/com/freediving/buddyservice/application/service/web/GetBuddyEventListingService.java
- buddy-service/src/main/java/com/freediving/divingpool/controller/DivingPoolInternalController.java
- buddy-service/src/test/java/com/freediving/buddyservice/application/service/CreateBuddyEventServiceTest.java
버디 모임 이벤트ID로 참여자 ID 조회
Closes #120
> feat: 버디 참여자 정보 제공

- member-service/src/main/java/com/freediving/memberservice/adapter/in/web/dto/FindMyPageResponse.java
- 유저 마이페이지 조회 API 응답 중복 데이터 제거
> refactor: #162 - 유저 마이페이지 조회 API 응답 중복 데이터 제거

- buddy-service/src/main/java/com/freediving/buddyservice/adapter/in/web/query/BuddyEventQueryController.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/createBuddyEventPersistenceAdapter.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/querydsl/caroselsimple/GetBuddyEventCarouselSimpleRepoDSL.java
- buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/querydsl/caroselsimple/GetBuddyEventCarouselSimpleRepoDSLImpl.java
- buddy-service/src/main/java/com/freediving/buddyservice/application/port/in/web/query/carouselsimple/GetBuddyEventCarouselSimpleCommand.java
- buddy-service/src/main/java/com/freediving/buddyservice/application/port/out/web/query/GetBuddyEventCarouselSimplePort.java
- buddy-service/src/main/java/com/freediving/buddyservice/application/service/web/GetBuddyEventCarouselSimpleService.java
feat: #176 내 관심 버디 모임 조회하기 개발.
> feat: #176 내 관심 버디 모임 조회하기 개발.

- .github/workflows/member-service-gcp.yml
- member-service/build.gradle
- member-service/src/main/java/com/freediving/authservice/adapter/in/web/TokenController.java
- member-service/src/main/java/com/freediving/authservice/adapter/out/persistence/token/FindTokenPersistenceAdapter.java
- member-service/src/main/java/com/freediving/authservice/util/JwtTokenUtils.java
- 리프레시 토큰 만료를 대비하여 존재하는 유저의 경우 액세스토큰을 생성하여 반환하도록 변경
> #194 - MemberService 샘플 토큰 생성 로직 변경

- community-service/src/main/resources/static/chatTest.html
> feat: 채팅방 실시간채팅
